language: python
python:
- '3.4'
- '3.5'
script: python -m unittest
notifications:
  slack:
    secure: osSl4OQbs0CirpL3m7ybBDUpU6yem0jhDOTdNev1SKUe/jsBcKKmfbOV8CIyNY4H746Q59RfyUMQJXzFBGR9d9pxf31WGeSQy8JWFOPCtZoKgCCDYaxoEgo2K8DsuIyCclQJBYo8iKVGdLICCSdxNghnqvS3mgp/FtPo84BVzFD/16T0N2GtFFfRVrESUHIcua8TD+/GwPhTKaBHpzlOZtS/MA/moI7O9qvZjsThD1XHLR0tcX1mBdU6O3exxjt+ooJmbjUKK9hMjQ42m0JI3Fkb8+qPGQRJmmUodZE0SzAoBkoTQCaiafV0lrFBpvYw7JlcZ5c9BYWCX4pN58l7rFvR3xtdp8pXLDbwK/BACKanMxZV0FdxmqD2dzYxztxljZY7c3644mGpyG20VK1r+EllHDcx7q8D+hafubfOlswxEfKGiJy0hvRaOX/9oS3VtQDq6knl/r/Y8eoYV4q4YLaSEOOsozHOJqIvrhsoL8LPhtKwwyQ25RU/9abfj/0z4mjIeNDOKxiRW04p3BirBJSXIii22Z6bgyODAq+/il6OuWxaKy5cY1BdipHLr4Iig6MxbYzBNGQO4beq6UQdk+ucMVzhV1fmi07DaT8ygHIAOcBuQoknAu2ocJDpJCbdO5F6sLzP65nN1xHGcAgPhQrsOjd4FIFjnhRl6KS8BdY=
